package com.arushi.typeahead.Repository;

import com.arushi.typeahead.Model.SearchTerm;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SearchRepository extends MongoRepository<SearchTerm, String> {
    //This allows fetching top 10 suggestions based on the prefix.
    //Queries are automatically generated by Spring Data MongoDB.
    List<SearchTerm> findTop10ByTermStartingWithOrderByFrequencyDesc(String prefix);
}
